// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dlgboyjnustnxwxnxsle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZ2JveWpudXN0bnh3eG54c2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzg5MzgsImV4cCI6MjA3Mzg1NDkzOH0.P3gESOvY9xHks20Bp1A6Lk5qyCdk4sVfrGMtll2kN2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});